name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Download Dependencies
        run: go get -v -t ./...

      - name: Go vet
        run: go vet ./...

      - name: Run Tests
        run: go test -v -race ./...